@startuml
hide footbox

' Participants

participant "Notebook" as notebook
participant "Spark" as spark
participant "DataAccess" as data_access
database "GCS" as gcs
participant "Catalog" as catalog
participant "UserAccess" as user_access

' Read data

note left of spark
    read("/path/to/dataset")
end note

activate notebook
notebook->spark ++ : read( path, options )
spark->data_access ++ : readLocation( path, snapshot )
spark-->notebook: logs
data_access->catalog ++ : getMetadata( path, snapshot )
return metadata
|||
data_access->user_access ++ : hasAccess( user, READ, path, valuation, state )
return allowed
return allowed, parentUri, version
spark-->notebook: logs
spark->data_access ++ : readAccessToken( path, version )
return accessToken, ttl, parentUri, version
|||
spark->gcs ++ : read( accessToken, URI.of( parentUri, path, version ) )
return parquet files
return logs
deactivate notebook

@enduml