@startuml

' Participants

participant "Jupyter Kernel\n(Spark, R, Python)" as kernel
participant "Storage" as storage
participant "data-access" as data_access
participant "Catalog" as catalog
participant "Metadata-distributor" as distributor
participant "PubSub events" as pubsubevents
participant "PubSub catalog" as pubsubcat


kernel->data_access ++: writeLocation
return signed metadata

kernel->storage ++: write data files (parquet)
return
kernel->storage ++: write metadata files (json)
return
kernel->storage ++: write signature file
return

kernel->catalog ++: <b>NEW:</b> write metadata and signature (low timeout, ignore failure)
catalog->catalog : <b>NEW:</b> validate metadata and signature
return

storage-->pubsubevents: publish signature file created event

pubsubevents-->distributor++: signature file created event
distributor->storage ++: read
return metadata files
distributor-->pubsubcat: publish metadata
deactivate

pubsubcat-->catalog++: metadata
catalog->catalog: update metadata

deactivate

@enduml