@startuml

start
:Execute Job;
if () then (read)
    :Get metadata;
    if (Get read \naccess-token) then
    else (denied)
        stop
    endif
    :Read data;
else (write)
    if (Check access &\n sign metadata) then
    else (denied)
        stop
    endif
    :Write metadata;
    :Write data;
    :Write signature;
    :Update catalog;
    :Update lineage;
endif
stop

@enduml
