@startuml

component "Zeppelin" as zeppelin
component "Zeppelin\nSpark\nInterpreter" as interpreter
component "User Access" as da_s
component "Catalog" as catalog
component "Data Access" as broker
database "Cloud Storage" as gcs {
}
frame "Executor" as worker {
  frame "Task" as task {
    [datasource] as datasource
    [gcs connector] as gcs_connector
  }
}

zeppelin -u-> interpreter : 1. submit job
interpreter -> worker : 2. distribute job
datasource --> broker : 3. read-location
broker --> catalog : 4. / 7. get metadata
broker --> da_s : 5. / 8. has-access?
gcs_connector --> broker : 6. get access-token
gcs_connector --> gcs : 9. read dataset


@enduml